### ISSUE TITLE
attempt to add a Permission to a readonly Permissions object

### ISSUE THREAD

**Issue by JeremJR** [pro-grade/pro-grade#29]
Hello,

I've tried to activate pro-grade on a Tomcat and I have an issue with the jasper lib included by tomcat 7.0.55:
To begin, the security file used allows all:
```
grant {
	permission java.security.AllPermission;
};
```
Unfortunately a webapp including a jsp raises the following stack trace:
```
GRAVE: Security Init for context failed
java.lang.SecurityException: attempt to add a Permission to a readonly Permissions object
	at java.security.Permissions.add(Permissions.java:127)
	at java.security.Policy$UnsupportedEmptyCollection.add(Policy.java:837)
	at org.apache.jasper.compiler.JspRuntimeContext.initSecurity(JspRuntimeContext.java:513)
	at org.apache.jasper.compiler.JspRuntimeContext.<init>(JspRuntimeContext.java:146)
	at org.apache.jasper.servlet.JspServlet.init(JspServlet.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:277)
	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:274)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAsPrivileged(Subject.java:536)
	at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:309)
	at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:169)
	at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:123)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1272)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1197)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1087)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5229)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5516)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
	at org.apache.catalina.core.ContainerBase.access$000(ContainerBase.java:133)
	at org.apache.catalina.core.ContainerBase$PrivilegedAddChild.run(ContainerBase.java:156)
	at org.apache.catalina.core.ContainerBase$PrivilegedAddChild.run(ContainerBase.java:145)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:875)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649)
	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:672)
	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1862)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```
It seems related to https://bz.apache.org/bugzilla/show_bug.cgi?id=41509

Note that when I use the default security manager with the same policy file, it doesn't raise any error.

Thanks in advance for your help.

**Comment by JeremJR** [comment]
In fact it seems that the exception was catched and there is no apparent impact in the jsp execution.

**Comment by kwart** [comment]
Hi,
thanks for the report. We know about this issue in Jasper - we hit it in JBoss AS 7.x (and EAP 6.x) too. Nevertheless it prints the exception and then it seems to work without problems.

As it's mentioned in the bug-report you've linked here, Jasper should not try to add the permissions on the first place. And if it really needs to do it in this way, then we would prefer only some warning message if the adding fails. The current solution - i.e. Exception in the error log - is not very clear from our point of view.

I'm closing this issue. If you think we can do more about it, then feel free to reopen it.

**Comment by bjorndarri** [comment]
I ran into this problem when generating a security policy for a custom RMI server I'm working on. After much ado I managed to fix (or work around) this issue by adding the following overrides to ProGradePolicy and NotifyAndAllowPolicy:

```java
@Override
public PermissionCollection getPermissions(final CodeSource codesource) {
    return new Permissions();
}

@Override
public PermissionCollection getPermissions(final ProtectionDomain domain) {
    final PermissionCollection permissions = super.getPermissions(domain);
    if (permissions == UNSUPPORTED_EMPTY_COLLECTION) {
        return new Permissions();
    }

    return permissions;
}
```
