### ISSUE TITLE
Generator fails to run with spring boot application

### ISSUE THREAD

**Issue by mooreds** [pro-grade/pro-grade#32]
Hi folks,

I was interested in running the generator against a spring boot application. However spring boot does some classpath mangling that appears to prevent pro-grade from running.

Here are the results:
```
$ java -Djava.security.manager=net.sourceforge.prograde.sm.PolicyFileGeneratorJSM -jar -Dprograde.generated.policy=/tmp/generated3.policy target/jar-1.5.2-SNAPSHOT.jar
Error occurred during initialization of VM
java.lang.InternalError: Could not create SecurityManager: net.sourceforge.prograde.sm.PolicyFileGeneratorJSM
        at sun.misc.Launcher.<init>(Launcher.java:106)
        at sun.misc.Launcher.<clinit>(Launcher.java:57)
        at java.lang.ClassLoader.initSystemClassLoader(ClassLoader.java:1445)
        at java.lang.ClassLoader.getSystemClassLoader(ClassLoader.java:1430)
```

I have verified I can run the app with very generous permissions:

```
grant {
  permission java.security.AllPermission;
};
```

I have also tried to use the ability spring boot has to unpack jar files (because it manages the classpath): https://docs.spring.io/spring-boot/docs/1.2.5.RELEASE/reference/html/howto-build.html#howto-extract-specific-libraries-when-an-executable-jar-runs

Here's the relevant maven section:

```
...
     <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${spring.boot.version}</version>
                <configuration>
                    <mainClass>com.mooreds.Runner</mainClass>
                    <layout>JAR</layout>
		    <requiresUnpack>
		      <dependency>
  			<groupId>net.sourceforge.pro-grade</groupId>
  			<artifactId>pro-grade</artifactId>
		      </dependency>
		    </requiresUnpack>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
...
```

But that doesn't seem to work--I get the same error message as above.

I was able to get the generator running directly in my IDE, but that is suboptimal since many of the paths were hardcoded and pointed into my compiled classes directories.

I'm using java 1.8.0_25, spring boot 1.2.5.RELEASE, version 1.1.1 of pro-grade.  

Would love to hear any suggestions or paths forward that I can explore.  I have googled around for "spring boot securitymanager" but haven't found anything.  This post https://github.com/spring-projects/spring-boot/issues/1117 touches on the issue, but I tried the java -D switch mentioned and it didn't work.

**Comment by mooreds** [comment]
This may be of interest.  https://github.com/spring-projects/spring-boot/pull/1669
